# Basic Info

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("/Users/rakeshm/Downloads/movie_data.txt",
                 delimiter="\t", names = ['ID', 'title', 'year', 'rating', 'votes', 'duration', 'genres'])

In [3]:
#df['ID'] = df.index

#can also be done by this
df.set_index('ID',inplace=True)

In [4]:
df
#df.set_index('ID',inplace=True)

,title,year,rating,votes,duration,genres
ID,,,,,,
tt0111161,The Shawshank Redemption (1994),1994,9.2,619479,142 mins.,Crime|Drama
tt0110912,Pulp Fiction (1994),1994,9.0,490065,154 mins.,Crime|Thriller
tt0137523,Fight Club (1999),1999,8.8,458173,139 mins.,Drama|Mystery|Thriller
tt0133093,The Matrix (1999),1999,8.7,448114,136 mins.,Action|Adventure|Sci-Fi
tt1375666,Inception (2010),2010,8.9,385149,148 mins.,Action|Adventure|Sci-Fi|Thriller
tt0109830,Forrest Gump (1994),1994,8.7,368994,142 mins.,Comedy|Drama|Romance
tt0169547,American Beauty (1999),1999,8.6,338332,122 mins.,Drama
tt0499549,Avatar (2009),2009,8.1,336855,162 mins.,Action|Adventure|Fantasy|Sci-Fi
tt0108052,Schindler's List (1993),1993,8.9,325888,195 mins.,Biography|Drama|History|War
tt0080684,Star Wars: Episode V - The Empire Strikes Back...,1980,8.8,320105,124 mins.,Action|Adventure|Family|Sci-Fi
tt0372784,Batman Begins (2005),2005,8.3,316613,140 mins.,Action|Crime|Drama|Thriller
tt0114814,The Usual Suspects (1995),1995,8.7,306624,106 mins.,Crime|Mystery|Thriller
tt0102926,The Silence of the Lambs (1991),1991,8.7,293081,118 mins.,Crime|Thriller
tt0120338,Titanic (1997),1997,7.4,284245,194 mins.,Adventure|Drama|History|Romance
tt0112573,Braveheart (1995),1995,8.4,281446,177 mins.,Action|Biography|Drama|History|War
tt0167404,The Sixth Sense (1999),1999,8.2,278210,107 mins.,Drama|Mystery|Thriller
tt0266697,Kill Bill: Vol. 1 (2003),2003,8.2,272983,111 mins.,Action|Crime|Thriller
tt0099685,Goodfellas (1990),1990,8.8,270728,146 mins.,Biography|Crime|Drama|Thriller
tt0416449,300 (2006),2006,7.8,269328,117 mins.,Action|Fantasy|History|War
tt0482571,The Prestige (2006),2006,8.4,258396,130 mins.,Drama|Mystery|Thriller
tt0105236,Reservoir Dogs (1992),1992,8.4,247390,99 mins.,Crime|Mystery|Thriller
tt0110413,Leon: The Professional (1994),1994,8.6,244568,110 mins.,Crime|Drama|Thriller
tt0120689,The Green Mile (1999),1999,8.4,243660,189 mins.,Crime|Drama|Fantasy|Mystery
tt0361748,Inglourious Basterds (2009),2009,8.4,240995,153 mins.,Adventure|Drama|War
tt0910970,WALL\xb7E (2008),2008,8.5,229364,98 mins.,Animation|Adventure|Family|Romance|Sci-Fi
tt0468569,The Dark Knight (2008),2008,8.9,555122,152 mins.,Action|Crime|Drama|Thriller
tt0068646,The Godfather (1972),1972,9.2,474189,175 mins.,Crime|Drama
tt0120737,The Lord of the Rings: The Fellowship of the R...,2001,8.8,451263,178 mins.,Action|Adventure|Drama|Fantasy
tt0167260,The Lord of the Rings: The Return of the King ...,2003,8.8,428791,201 mins.,Action|Adventure|Drama|Fantasy
tt0167261,The Lord of the Rings: The Two Towers (2002),2002,8.7,383113,179 mins.,Action|Adventure|Drama|Fantasy
...,...,...,...,...,...,...
tt0469897,Diggers (2006),2006,6.4,1358,96 mins.,Comedy|Drama
tt0110064,House Party 3 (1994),1994,3.1,1357,100 mins.,Comedy|Music|Romance
tt1629391,Tere Bin Laden (2010),2010,7.2,1357,95 mins.,Comedy|Drama
tt0878674,Garage (2007),2007,6.9,1356,00 mins.,Drama
tt0076391,Mimino (1977),1977,8.2,1356,97 mins.,Comedy
tt1316037,Birdemic: Shock and Terror (2008),2008,2.0,1366,90 mins.,Horror|Romance|Thriller
tt0197094,What Becomes of the Broken Hearted? (1999),1999,6.3,1365,00 mins.,Drama
tt0092608,Back to the Beach (1987),1987,5.1,1364,92 mins.,Comedy
tt0093175,Hello Again (1987),1987,4.5,1364,96 mins.,Comedy|Drama|Fantasy|Romance
tt1034320,Major Movie Star (2008),2008,3.8,1364,98 mins.,Adventure|Comedy|Drama|War
tt0066476,The Touch of Satan (1971),1971,2.0,1364,90 mins.,Horror
tt1281374,Don McKay (2009),2009,6.0,1363,87 mins.,Drama|Thriller|Mystery
tt0263124,Brainstorm (2001),2001,7.8,1362,74 mins.,Drama
tt0368259,Sex Lives of the Potato Men (2004),2004,4.3,1362,82 mins.,Comedy
tt0067333,Lawman (1971),1971,6.8,1362,99 mins.,Western
tt0065669,The Dunwich Horror (1970),1970,5.1,1361,90 mins.,Horror
tt0048198,I Live in Fear (1955),1955,7.3,1360,103 mins.,Drama
tt0100046,The Long Walk Home (1990),1990,7.2,1360,97 mins.,Drama|History
tt0116247,Evil Ed (1995),1995,5.0,1359,93 mins.,Horror|Comedy
tt0101356,Another You (1991),1991,4.9,1359,98 mins.,Comedy|Crime
tt0421090,Zerophilia (2005),2005,6.3,1359,90 mins.,Comedy|Romance
tt0067227,The Merchant of Four Seasons (1971),1971,7.6,1359,88 mins.,Drama
tt0339727,Stateside (2004),2004,5.8,1358,97 mins.,Drama|Music|Romance
tt0218581,Scarlet Diva (2000),2000,5.2,1358,91 mins.,Drama
tt0118635,Aprile (1998),1998,6.7,1358,78 mins.,Comedy
tt0807721,Meduzot (2007),2007,7.0,1357,78 mins.,Drama
tt0339642,Daltry Calhoun (2005),2005,5.2,1357,100 mins.,Comedy|Drama|Music|Romance
tt0060880,The Quiller Memorandum (1966),1966,6.5,1356,104 mins.,Drama|Mystery|Thriller
tt0152836,Taal (1999),1999,6.5,1356,179 mins.,Musical|Romance
tt0279977,The Navigators (2001),2001,6.9,1356,96 mins.,Comedy|Drama

In [5]:
df.head()

,title,year,rating,votes,duration,genres
ID,,,,,,
tt0111161,The Shawshank Redemption (1994),1994,9.2,619479,142 mins.,Crime|Drama
tt0110912,Pulp Fiction (1994),1994,9.0,490065,154 mins.,Crime|Thriller
tt0137523,Fight Club (1999),1999,8.8,458173,139 mins.,Drama|Mystery|Thriller
tt0133093,The Matrix (1999),1999,8.7,448114,136 mins.,Action|Adventure|Sci-Fi
tt1375666,Inception (2010),2010,8.9,385149,148 mins.,Action|Adventure|Sci-Fi|Thriller

In [6]:
df.tail(11)

,title,year,rating,votes,duration,genres
ID,,,,,,
tt0101356,Another You (1991),1991,4.9,1359,98 mins.,Comedy|Crime
tt0421090,Zerophilia (2005),2005,6.3,1359,90 mins.,Comedy|Romance
tt0067227,The Merchant of Four Seasons (1971),1971,7.6,1359,88 mins.,Drama
tt0339727,Stateside (2004),2004,5.8,1358,97 mins.,Drama|Music|Romance
tt0218581,Scarlet Diva (2000),2000,5.2,1358,91 mins.,Drama
tt0118635,Aprile (1998),1998,6.7,1358,78 mins.,Comedy
tt0807721,Meduzot (2007),2007,7.0,1357,78 mins.,Drama
tt0339642,Daltry Calhoun (2005),2005,5.2,1357,100 mins.,Comedy|Drama|Music|Romance
tt0060880,The Quiller Memorandum (1966),1966,6.5,1356,104 mins.,Drama|Mystery|Thriller
tt0152836,Taal (1999),1999,6.5,1356,179 mins.,Musical|Romance
tt0279977,The Navigators (2001),2001,6.9,1356,96 mins.,Comedy|Drama

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, tt0111161 to tt0279977
Data columns (total 6 columns):
title       10000 non-null object
year        10000 non-null int64
rating      10000 non-null float64
votes       10000 non-null int64
duration    10000 non-null object
genres      9999 non-null object
dtypes: float64(1), int64(2), object(3)
memory usage: 546.9+ KB

# Cleaning

In [8]:
df

,title,year,rating,votes,duration,genres
ID,,,,,,
tt0111161,The Shawshank Redemption (1994),1994,9.2,619479,142 mins.,Crime|Drama
tt0110912,Pulp Fiction (1994),1994,9.0,490065,154 mins.,Crime|Thriller
tt0137523,Fight Club (1999),1999,8.8,458173,139 mins.,Drama|Mystery|Thriller
tt0133093,The Matrix (1999),1999,8.7,448114,136 mins.,Action|Adventure|Sci-Fi
tt1375666,Inception (2010),2010,8.9,385149,148 mins.,Action|Adventure|Sci-Fi|Thriller
tt0109830,Forrest Gump (1994),1994,8.7,368994,142 mins.,Comedy|Drama|Romance
tt0169547,American Beauty (1999),1999,8.6,338332,122 mins.,Drama
tt0499549,Avatar (2009),2009,8.1,336855,162 mins.,Action|Adventure|Fantasy|Sci-Fi
tt0108052,Schindler's List (1993),1993,8.9,325888,195 mins.,Biography|Drama|History|War
tt0080684,Star Wars: Episode V - The Empire Strikes Back...,1980,8.8,320105,124 mins.,Action|Adventure|Family|Sci-Fi
tt0372784,Batman Begins (2005),2005,8.3,316613,140 mins.,Action|Crime|Drama|Thriller
tt0114814,The Usual Suspects (1995),1995,8.7,306624,106 mins.,Crime|Mystery|Thriller
tt0102926,The Silence of the Lambs (1991),1991,8.7,293081,118 mins.,Crime|Thriller
tt0120338,Titanic (1997),1997,7.4,284245,194 mins.,Adventure|Drama|History|Romance
tt0112573,Braveheart (1995),1995,8.4,281446,177 mins.,Action|Biography|Drama|History|War
tt0167404,The Sixth Sense (1999),1999,8.2,278210,107 mins.,Drama|Mystery|Thriller
tt0266697,Kill Bill: Vol. 1 (2003),2003,8.2,272983,111 mins.,Action|Crime|Thriller
tt0099685,Goodfellas (1990),1990,8.8,270728,146 mins.,Biography|Crime|Drama|Thriller
tt0416449,300 (2006),2006,7.8,269328,117 mins.,Action|Fantasy|History|War
tt0482571,The Prestige (2006),2006,8.4,258396,130 mins.,Drama|Mystery|Thriller
tt0105236,Reservoir Dogs (1992),1992,8.4,247390,99 mins.,Crime|Mystery|Thriller
tt0110413,Leon: The Professional (1994),1994,8.6,244568,110 mins.,Crime|Drama|Thriller
tt0120689,The Green Mile (1999),1999,8.4,243660,189 mins.,Crime|Drama|Fantasy|Mystery
tt0361748,Inglourious Basterds (2009),2009,8.4,240995,153 mins.,Adventure|Drama|War
tt0910970,WALL\xb7E (2008),2008,8.5,229364,98 mins.,Animation|Adventure|Family|Romance|Sci-Fi
tt0468569,The Dark Knight (2008),2008,8.9,555122,152 mins.,Action|Crime|Drama|Thriller
tt0068646,The Godfather (1972),1972,9.2,474189,175 mins.,Crime|Drama
tt0120737,The Lord of the Rings: The Fellowship of the R...,2001,8.8,451263,178 mins.,Action|Adventure|Drama|Fantasy
tt0167260,The Lord of the Rings: The Return of the King ...,2003,8.8,428791,201 mins.,Action|Adventure|Drama|Fantasy
tt0167261,The Lord of the Rings: The Two Towers (2002),2002,8.7,383113,179 mins.,Action|Adventure|Drama|Fantasy
...,...,...,...,...,...,...
tt0469897,Diggers (2006),2006,6.4,1358,96 mins.,Comedy|Drama
tt0110064,House Party 3 (1994),1994,3.1,1357,100 mins.,Comedy|Music|Romance
tt1629391,Tere Bin Laden (2010),2010,7.2,1357,95 mins.,Comedy|Drama
tt0878674,Garage (2007),2007,6.9,1356,00 mins.,Drama
tt0076391,Mimino (1977),1977,8.2,1356,97 mins.,Comedy
tt1316037,Birdemic: Shock and Terror (2008),2008,2.0,1366,90 mins.,Horror|Romance|Thriller
tt0197094,What Becomes of the Broken Hearted? (1999),1999,6.3,1365,00 mins.,Drama
tt0092608,Back to the Beach (1987),1987,5.1,1364,92 mins.,Comedy
tt0093175,Hello Again (1987),1987,4.5,1364,96 mins.,Comedy|Drama|Fantasy|Romance
tt1034320,Major Movie Star (2008),2008,3.8,1364,98 mins.,Adventure|Comedy|Drama|War
tt0066476,The Touch of Satan (1971),1971,2.0,1364,90 mins.,Horror
tt1281374,Don McKay (2009),2009,6.0,1363,87 mins.,Drama|Thriller|Mystery
tt0263124,Brainstorm (2001),2001,7.8,1362,74 mins.,Drama
tt0368259,Sex Lives of the Potato Men (2004),2004,4.3,1362,82 mins.,Comedy
tt0067333,Lawman (1971),1971,6.8,1362,99 mins.,Western
tt0065669,The Dunwich Horror (1970),1970,5.1,1361,90 mins.,Horror
tt0048198,I Live in Fear (1955),1955,7.3,1360,103 mins.,Drama
tt0100046,The Long Walk Home (1990),1990,7.2,1360,97 mins.,Drama|History
tt0116247,Evil Ed (1995),1995,5.0,1359,93 mins.,Horror|Comedy
tt0101356,Another You (1991),1991,4.9,1359,98 mins.,Comedy|Crime
tt0421090,Zerophilia (2005),2005,6.3,1359,90 mins.,Comedy|Romance
tt0067227,The Merchant of Four Seasons (1971),1971,7.6,1359,88 mins.,Drama
tt0339727,Stateside (2004),2004,5.8,1358,97 mins.,Drama|Music|Romance
tt0218581,Scarlet Diva (2000),2000,5.2,1358,91 mins.,Drama
tt0118635,Aprile (1998),1998,6.7,1358,78 mins.,Comedy
tt0807721,Meduzot (2007),2007,7.0,1357,78 mins.,Drama
tt0339642,Daltry Calhoun (2005),2005,5.2,1357,100 mins.,Comedy|Drama|Music|Romance
tt0060880,The Quiller Memorandum (1966),1966,6.5,1356,104 mins.,Drama|Mystery|Thriller
tt0152836,Taal (1999),1999,6.5,1356,179 mins.,Musical|Romance
tt0279977,The Navigators (2001),2001,6.9,1356,96 mins.,Comedy|Drama

In [9]:
null_row = df[df.isnull().any(axis=1)]

In [10]:
null_row

                      title  year  rating  votes  duration genres
ID
tt0990404  Chop Shop (2007)  2007     7.2   2104  84 mins.    NaN

In [11]:
df.dropna(inplace=True)

In [12]:
df

,title,year,rating,votes,duration,genres
ID,,,,,,
tt0111161,The Shawshank Redemption (1994),1994,9.2,619479,142 mins.,Crime|Drama
tt0110912,Pulp Fiction (1994),1994,9.0,490065,154 mins.,Crime|Thriller
tt0137523,Fight Club (1999),1999,8.8,458173,139 mins.,Drama|Mystery|Thriller
tt0133093,The Matrix (1999),1999,8.7,448114,136 mins.,Action|Adventure|Sci-Fi
tt1375666,Inception (2010),2010,8.9,385149,148 mins.,Action|Adventure|Sci-Fi|Thriller
tt0109830,Forrest Gump (1994),1994,8.7,368994,142 mins.,Comedy|Drama|Romance
tt0169547,American Beauty (1999),1999,8.6,338332,122 mins.,Drama
tt0499549,Avatar (2009),2009,8.1,336855,162 mins.,Action|Adventure|Fantasy|Sci-Fi
tt0108052,Schindler's List (1993),1993,8.9,325888,195 mins.,Biography|Drama|History|War
tt0080684,Star Wars: Episode V - The Empire Strikes Back...,1980,8.8,320105,124 mins.,Action|Adventure|Family|Sci-Fi
tt0372784,Batman Begins (2005),2005,8.3,316613,140 mins.,Action|Crime|Drama|Thriller
tt0114814,The Usual Suspects (1995),1995,8.7,306624,106 mins.,Crime|Mystery|Thriller
tt0102926,The Silence of the Lambs (1991),1991,8.7,293081,118 mins.,Crime|Thriller
tt0120338,Titanic (1997),1997,7.4,284245,194 mins.,Adventure|Drama|History|Romance
tt0112573,Braveheart (1995),1995,8.4,281446,177 mins.,Action|Biography|Drama|History|War
tt0167404,The Sixth Sense (1999),1999,8.2,278210,107 mins.,Drama|Mystery|Thriller
tt0266697,Kill Bill: Vol. 1 (2003),2003,8.2,272983,111 mins.,Action|Crime|Thriller
tt0099685,Goodfellas (1990),1990,8.8,270728,146 mins.,Biography|Crime|Drama|Thriller
tt0416449,300 (2006),2006,7.8,269328,117 mins.,Action|Fantasy|History|War
tt0482571,The Prestige (2006),2006,8.4,258396,130 mins.,Drama|Mystery|Thriller
tt0105236,Reservoir Dogs (1992),1992,8.4,247390,99 mins.,Crime|Mystery|Thriller
tt0110413,Leon: The Professional (1994),1994,8.6,244568,110 mins.,Crime|Drama|Thriller
tt0120689,The Green Mile (1999),1999,8.4,243660,189 mins.,Crime|Drama|Fantasy|Mystery
tt0361748,Inglourious Basterds (2009),2009,8.4,240995,153 mins.,Adventure|Drama|War
tt0910970,WALL\xb7E (2008),2008,8.5,229364,98 mins.,Animation|Adventure|Family|Romance|Sci-Fi
tt0468569,The Dark Knight (2008),2008,8.9,555122,152 mins.,Action|Crime|Drama|Thriller
tt0068646,The Godfather (1972),1972,9.2,474189,175 mins.,Crime|Drama
tt0120737,The Lord of the Rings: The Fellowship of the R...,2001,8.8,451263,178 mins.,Action|Adventure|Drama|Fantasy
tt0167260,The Lord of the Rings: The Return of the King ...,2003,8.8,428791,201 mins.,Action|Adventure|Drama|Fantasy
tt0167261,The Lord of the Rings: The Two Towers (2002),2002,8.7,383113,179 mins.,Action|Adventure|Drama|Fantasy
...,...,...,...,...,...,...
tt0469897,Diggers (2006),2006,6.4,1358,96 mins.,Comedy|Drama
tt0110064,House Party 3 (1994),1994,3.1,1357,100 mins.,Comedy|Music|Romance
tt1629391,Tere Bin Laden (2010),2010,7.2,1357,95 mins.,Comedy|Drama
tt0878674,Garage (2007),2007,6.9,1356,00 mins.,Drama
tt0076391,Mimino (1977),1977,8.2,1356,97 mins.,Comedy
tt1316037,Birdemic: Shock and Terror (2008),2008,2.0,1366,90 mins.,Horror|Romance|Thriller
tt0197094,What Becomes of the Broken Hearted? (1999),1999,6.3,1365,00 mins.,Drama
tt0092608,Back to the Beach (1987),1987,5.1,1364,92 mins.,Comedy
tt0093175,Hello Again (1987),1987,4.5,1364,96 mins.,Comedy|Drama|Fantasy|Romance
tt1034320,Major Movie Star (2008),2008,3.8,1364,98 mins.,Adventure|Comedy|Drama|War
tt0066476,The Touch of Satan (1971),1971,2.0,1364,90 mins.,Horror
tt1281374,Don McKay (2009),2009,6.0,1363,87 mins.,Drama|Thriller|Mystery
tt0263124,Brainstorm (2001),2001,7.8,1362,74 mins.,Drama
tt0368259,Sex Lives of the Potato Men (2004),2004,4.3,1362,82 mins.,Comedy
tt0067333,Lawman (1971),1971,6.8,1362,99 mins.,Western
tt0065669,The Dunwich Horror (1970),1970,5.1,1361,90 mins.,Horror
tt0048198,I Live in Fear (1955),1955,7.3,1360,103 mins.,Drama
tt0100046,The Long Walk Home (1990),1990,7.2,1360,97 mins.,Drama|History
tt0116247,Evil Ed (1995),1995,5.0,1359,93 mins.,Horror|Comedy
tt0101356,Another You (1991),1991,4.9,1359,98 mins.,Comedy|Crime
tt0421090,Zerophilia (2005),2005,6.3,1359,90 mins.,Comedy|Romance
tt0067227,The Merchant of Four Seasons (1971),1971,7.6,1359,88 mins.,Drama
tt0339727,Stateside (2004),2004,5.8,1358,97 mins.,Drama|Music|Romance
tt0218581,Scarlet Diva (2000),2000,5.2,1358,91 mins.,Drama
tt0118635,Aprile (1998),1998,6.7,1358,78 mins.,Comedy
tt0807721,Meduzot (2007),2007,7.0,1357,78 mins.,Drama
tt0339642,Daltry Calhoun (2005),2005,5.2,1357,100 mins.,Comedy|Drama|Music|Romance
tt0060880,The Quiller Memorandum (1966),1966,6.5,1356,104 mins.,Drama|Mystery|Thriller
tt0152836,Taal (1999),1999,6.5,1356,179 mins.,Musical|Romance
tt0279977,The Navigators (2001),2001,6.9,1356,96 mins.,Comedy|Drama

In [13]:
nulll = df[df.isnull().any(axis=1)]

In [14]:
nulll

Empty DataFrame
Columns: [title, year, rating, votes, duration, genres]
Index: []

In [15]:
df['duration'] = df['duration'].apply(lambda x : int(x.replace("mins.", '')))

In [16]:
df['duration'] = df['duration'] * 60

In [17]:
df

,title,year,rating,votes,duration,genres
ID,,,,,,
tt0111161,The Shawshank Redemption (1994),1994,9.2,619479,8520,Crime|Drama
tt0110912,Pulp Fiction (1994),1994,9.0,490065,9240,Crime|Thriller
tt0137523,Fight Club (1999),1999,8.8,458173,8340,Drama|Mystery|Thriller
tt0133093,The Matrix (1999),1999,8.7,448114,8160,Action|Adventure|Sci-Fi
tt1375666,Inception (2010),2010,8.9,385149,8880,Action|Adventure|Sci-Fi|Thriller
tt0109830,Forrest Gump (1994),1994,8.7,368994,8520,Comedy|Drama|Romance
tt0169547,American Beauty (1999),1999,8.6,338332,7320,Drama
tt0499549,Avatar (2009),2009,8.1,336855,9720,Action|Adventure|Fantasy|Sci-Fi
tt0108052,Schindler's List (1993),1993,8.9,325888,11700,Biography|Drama|History|War
tt0080684,Star Wars: Episode V - The Empire Strikes Back...,1980,8.8,320105,7440,Action|Adventure|Family|Sci-Fi
tt0372784,Batman Begins (2005),2005,8.3,316613,8400,Action|Crime|Drama|Thriller
tt0114814,The Usual Suspects (1995),1995,8.7,306624,6360,Crime|Mystery|Thriller
tt0102926,The Silence of the Lambs (1991),1991,8.7,293081,7080,Crime|Thriller
tt0120338,Titanic (1997),1997,7.4,284245,11640,Adventure|Drama|History|Romance
tt0112573,Braveheart (1995),1995,8.4,281446,10620,Action|Biography|Drama|History|War
tt0167404,The Sixth Sense (1999),1999,8.2,278210,6420,Drama|Mystery|Thriller
tt0266697,Kill Bill: Vol. 1 (2003),2003,8.2,272983,6660,Action|Crime|Thriller
tt0099685,Goodfellas (1990),1990,8.8,270728,8760,Biography|Crime|Drama|Thriller
tt0416449,300 (2006),2006,7.8,269328,7020,Action|Fantasy|History|War
tt0482571,The Prestige (2006),2006,8.4,258396,7800,Drama|Mystery|Thriller
tt0105236,Reservoir Dogs (1992),1992,8.4,247390,5940,Crime|Mystery|Thriller
tt0110413,Leon: The Professional (1994),1994,8.6,244568,6600,Crime|Drama|Thriller
tt0120689,The Green Mile (1999),1999,8.4,243660,11340,Crime|Drama|Fantasy|Mystery
tt0361748,Inglourious Basterds (2009),2009,8.4,240995,9180,Adventure|Drama|War
tt0910970,WALL\xb7E (2008),2008,8.5,229364,5880,Animation|Adventure|Family|Romance|Sci-Fi
tt0468569,The Dark Knight (2008),2008,8.9,555122,9120,Action|Crime|Drama|Thriller
tt0068646,The Godfather (1972),1972,9.2,474189,10500,Crime|Drama
tt0120737,The Lord of the Rings: The Fellowship of the R...,2001,8.8,451263,10680,Action|Adventure|Drama|Fantasy
tt0167260,The Lord of the Rings: The Return of the King ...,2003,8.8,428791,12060,Action|Adventure|Drama|Fantasy
tt0167261,The Lord of the Rings: The Two Towers (2002),2002,8.7,383113,10740,Action|Adventure|Drama|Fantasy
...,...,...,...,...,...,...
tt0469897,Diggers (2006),2006,6.4,1358,5760,Comedy|Drama
tt0110064,House Party 3 (1994),1994,3.1,1357,6000,Comedy|Music|Romance
tt1629391,Tere Bin Laden (2010),2010,7.2,1357,5700,Comedy|Drama
tt0878674,Garage (2007),2007,6.9,1356,0,Drama
tt0076391,Mimino (1977),1977,8.2,1356,5820,Comedy
tt1316037,Birdemic: Shock and Terror (2008),2008,2.0,1366,5400,Horror|Romance|Thriller
tt0197094,What Becomes of the Broken Hearted? (1999),1999,6.3,1365,0,Drama
tt0092608,Back to the Beach (1987),1987,5.1,1364,5520,Comedy
tt0093175,Hello Again (1987),1987,4.5,1364,5760,Comedy|Drama|Fantasy|Romance
tt1034320,Major Movie Star (2008),2008,3.8,1364,5880,Adventure|Comedy|Drama|War
tt0066476,The Touch of Satan (1971),1971,2.0,1364,5400,Horror
tt1281374,Don McKay (2009),2009,6.0,1363,5220,Drama|Thriller|Mystery
tt0263124,Brainstorm (2001),2001,7.8,1362,4440,Drama
tt0368259,Sex Lives of the Potato Men (2004),2004,4.3,1362,4920,Comedy
tt0067333,Lawman (1971),1971,6.8,1362,5940,Western
tt0065669,The Dunwich Horror (1970),1970,5.1,1361,5400,Horror
tt0048198,I Live in Fear (1955),1955,7.3,1360,6180,Drama
tt0100046,The Long Walk Home (1990),1990,7.2,1360,5820,Drama|History
tt0116247,Evil Ed (1995),1995,5.0,1359,5580,Horror|Comedy
tt0101356,Another You (1991),1991,4.9,1359,5880,Comedy|Crime
tt0421090,Zerophilia (2005),2005,6.3,1359,5400,Comedy|Romance
tt0067227,The Merchant of Four Seasons (1971),1971,7.6,1359,5280,Drama
tt0339727,Stateside (2004),2004,5.8,1358,5820,Drama|Music|Romance
tt0218581,Scarlet Diva (2000),2000,5.2,1358,5460,Drama
tt0118635,Aprile (1998),1998,6.7,1358,4680,Comedy
tt0807721,Meduzot (2007),2007,7.0,1357,4680,Drama
tt0339642,Daltry Calhoun (2005),2005,5.2,1357,6000,Comedy|Drama|Music|Romance
tt0060880,The Quiller Memorandum (1966),1966,6.5,1356,6240,Drama|Mystery|Thriller
tt0152836,Taal (1999),1999,6.5,1356,10740,Musical|Romance
tt0279977,The Navigators (2001),2001,6.9,1356,5760,Comedy|Drama

In [18]:
df['title'] = df['title'].apply(lambda x : x[:-6])

In [19]:
df

,title,year,rating,votes,duration,genres
ID,,,,,,
tt0111161,The Shawshank Redemption,1994,9.2,619479,8520,Crime|Drama
tt0110912,Pulp Fiction,1994,9.0,490065,9240,Crime|Thriller
tt0137523,Fight Club,1999,8.8,458173,8340,Drama|Mystery|Thriller
tt0133093,The Matrix,1999,8.7,448114,8160,Action|Adventure|Sci-Fi
tt1375666,Inception,2010,8.9,385149,8880,Action|Adventure|Sci-Fi|Thriller
tt0109830,Forrest Gump,1994,8.7,368994,8520,Comedy|Drama|Romance
tt0169547,American Beauty,1999,8.6,338332,7320,Drama
tt0499549,Avatar,2009,8.1,336855,9720,Action|Adventure|Fantasy|Sci-Fi
tt0108052,Schindler's List,1993,8.9,325888,11700,Biography|Drama|History|War
tt0080684,Star Wars: Episode V - The Empire Strikes Back,1980,8.8,320105,7440,Action|Adventure|Family|Sci-Fi
tt0372784,Batman Begins,2005,8.3,316613,8400,Action|Crime|Drama|Thriller
tt0114814,The Usual Suspects,1995,8.7,306624,6360,Crime|Mystery|Thriller
tt0102926,The Silence of the Lambs,1991,8.7,293081,7080,Crime|Thriller
tt0120338,Titanic,1997,7.4,284245,11640,Adventure|Drama|History|Romance
tt0112573,Braveheart,1995,8.4,281446,10620,Action|Biography|Drama|History|War
tt0167404,The Sixth Sense,1999,8.2,278210,6420,Drama|Mystery|Thriller
tt0266697,Kill Bill: Vol. 1,2003,8.2,272983,6660,Action|Crime|Thriller
tt0099685,Goodfellas,1990,8.8,270728,8760,Biography|Crime|Drama|Thriller
tt0416449,300,2006,7.8,269328,7020,Action|Fantasy|History|War
tt0482571,The Prestige,2006,8.4,258396,7800,Drama|Mystery|Thriller
tt0105236,Reservoir Dogs,1992,8.4,247390,5940,Crime|Mystery|Thriller
tt0110413,Leon: The Professional,1994,8.6,244568,6600,Crime|Drama|Thriller
tt0120689,The Green Mile,1999,8.4,243660,11340,Crime|Drama|Fantasy|Mystery
tt0361748,Inglourious Basterds,2009,8.4,240995,9180,Adventure|Drama|War
tt0910970,WALL\xb7E,2008,8.5,229364,5880,Animation|Adventure|Family|Romance|Sci-Fi
tt0468569,The Dark Knight,2008,8.9,555122,9120,Action|Crime|Drama|Thriller
tt0068646,The Godfather,1972,9.2,474189,10500,Crime|Drama
tt0120737,The Lord of the Rings: The Fellowship of the R...,2001,8.8,451263,10680,Action|Adventure|Drama|Fantasy
tt0167260,The Lord of the Rings: The Return of the King,2003,8.8,428791,12060,Action|Adventure|Drama|Fantasy
tt0167261,The Lord of the Rings: The Two Towers,2002,8.7,383113,10740,Action|Adventure|Drama|Fantasy
...,...,...,...,...,...,...
tt0469897,Diggers,2006,6.4,1358,5760,Comedy|Drama
tt0110064,House Party 3,1994,3.1,1357,6000,Comedy|Music|Romance
tt1629391,Tere Bin Laden,2010,7.2,1357,5700,Comedy|Drama
tt0878674,Garage,2007,6.9,1356,0,Drama
tt0076391,Mimino,1977,8.2,1356,5820,Comedy
tt1316037,Birdemic: Shock and Terror,2008,2.0,1366,5400,Horror|Romance|Thriller
tt0197094,What Becomes of the Broken Hearted?,1999,6.3,1365,0,Drama
tt0092608,Back to the Beach,1987,5.1,1364,5520,Comedy
tt0093175,Hello Again,1987,4.5,1364,5760,Comedy|Drama|Fantasy|Romance
tt1034320,Major Movie Star,2008,3.8,1364,5880,Adventure|Comedy|Drama|War
tt0066476,The Touch of Satan,1971,2.0,1364,5400,Horror
tt1281374,Don McKay,2009,6.0,1363,5220,Drama|Thriller|Mystery
tt0263124,Brainstorm,2001,7.8,1362,4440,Drama
tt0368259,Sex Lives of the Potato Men,2004,4.3,1362,4920,Comedy
tt0067333,Lawman,1971,6.8,1362,5940,Western
tt0065669,The Dunwich Horror,1970,5.1,1361,5400,Horror
tt0048198,I Live in Fear,1955,7.3,1360,6180,Drama
tt0100046,The Long Walk Home,1990,7.2,1360,5820,Drama|History
tt0116247,Evil Ed,1995,5.0,1359,5580,Horror|Comedy
tt0101356,Another You,1991,4.9,1359,5880,Comedy|Crime
tt0421090,Zerophilia,2005,6.3,1359,5400,Comedy|Romance
tt0067227,The Merchant of Four Seasons,1971,7.6,1359,5280,Drama
tt0339727,Stateside,2004,5.8,1358,5820,Drama|Music|Romance
tt0218581,Scarlet Diva,2000,5.2,1358,5460,Drama
tt0118635,Aprile,1998,6.7,1358,4680,Comedy
tt0807721,Meduzot,2007,7.0,1357,4680,Drama
tt0339642,Daltry Calhoun,2005,5.2,1357,6000,Comedy|Drama|Music|Romance
tt0060880,The Quiller Memorandum,1966,6.5,1356,6240,Drama|Mystery|Thriller
tt0152836,Taal,1999,6.5,1356,10740,Musical|Romance
tt0279977,The Navigators,2001,6.9,1356,5760,Comedy|Drama

# Concatenating

In [20]:
movie_crew_df = pd.read_csv('/Users/rakeshm/downloads/crew_data.tsv.gz', header = 0, delimiter = '\t', usecols=(0,1),
                            names = ['ID', 'director_ids'])

In [21]:
movie_crew_df

                ID         director_ids
0        tt0000001            nm0005690
1        tt0000002            nm0721526
2        tt0000003            nm0721526
3        tt0000004            nm0721526
4        tt0000005            nm0005690
5        tt0000006            nm0005690
6        tt0000007  nm0005690,nm0374658
7        tt0000008            nm0005690
8        tt0000009            nm0085156
9        tt0000010            nm0525910
10       tt0000011            nm0804434
11       tt0000012  nm0525908,nm0525910
12       tt0000013            nm0525910
13       tt0000014            nm0525910
14       tt0000015            nm0721526
15       tt0000016            nm0525910
16       tt0000017  nm0804434,nm1587194
17       tt0000018            nm0804434
18       tt0000019            nm0932055
19       tt0000020            nm0010291
20       tt0000022            nm0525910
21       tt0000023            nm0525910
22       tt0000024            nm0010291
23       tt0000025            nm0010291
24       tt0000026            nm0525910
25       tt0000027            nm0525910
26       tt0000028            nm0525910
27       tt0000029            nm0525910
28       tt0000030  nm0666972,nm0010291
29       tt0000031            nm0525910
...            ...                  ...
5953900  tt9916796  nm5519454,nm5519375
5953901  tt9916798  nm5519454,nm5519375
5953902  tt9916800  nm5519375,nm5519454
5953903  tt9916802                   \N
5953904  tt9916804  nm5519375,nm5519454
5953905  tt9916806  nm5519375,nm5519454
5953906  tt9916808  nm5519375,nm5519454
5953907  tt9916810                   \N
5953908  tt9916812  nm5519454,nm5519375
5953909  tt9916814  nm5519454,nm5519375
5953910  tt9916816  nm5519375,nm5519454
5953911  tt9916818  nm5519454,nm5519375
5953912  tt9916820  nm5519375,nm5519454
5953913  tt9916822  nm5519454,nm5519375
5953914  tt9916824  nm5519454,nm5519375
5953915  tt9916826  nm5519375,nm5519454
5953916  tt9916830            nm4289598
5953917  tt9916832  nm5519454,nm5519375
5953918  tt9916834  nm5519454,nm5519375
5953919  tt9916836  nm5519454,nm5519375
5953920  tt9916838  nm5519375,nm5519454
5953921  tt9916840            nm0996406
5953922  tt9916842  nm5519375,nm5519454
5953923  tt9916844  nm5519375,nm5519454
5953924  tt9916846  nm5519454,nm5519375
5953925  tt9916848  nm5519375,nm5519454
5953926  tt9916850  nm5519375,nm5519454
5953927  tt9916852  nm5519375,nm5519454
5953928  tt9916856           nm10538645
5953929  tt9916880            nm0996406

[5953930 rows x 2 columns]

In [22]:
#movie_crew_df['ID'] = movie_crew_df.index
movie_crew_df.set_index('ID', inplace =True)
movie_crew_df

                  director_ids
ID
tt0000001            nm0005690
tt0000002            nm0721526
tt0000003            nm0721526
tt0000004            nm0721526
tt0000005            nm0005690
tt0000006            nm0005690
tt0000007  nm0005690,nm0374658
tt0000008            nm0005690
tt0000009            nm0085156
tt0000010            nm0525910
tt0000011            nm0804434
tt0000012  nm0525908,nm0525910
tt0000013            nm0525910
tt0000014            nm0525910
tt0000015            nm0721526
tt0000016            nm0525910
tt0000017  nm0804434,nm1587194
tt0000018            nm0804434
tt0000019            nm0932055
tt0000020            nm0010291
tt0000022            nm0525910
tt0000023            nm0525910
tt0000024            nm0010291
tt0000025            nm0010291
tt0000026            nm0525910
tt0000027            nm0525910
tt0000028            nm0525910
tt0000029            nm0525910
tt0000030  nm0666972,nm0010291
tt0000031            nm0525910
...                        ...
tt9916796  nm5519454,nm5519375
tt9916798  nm5519454,nm5519375
tt9916800  nm5519375,nm5519454
tt9916802                   \N
tt9916804  nm5519375,nm5519454
tt9916806  nm5519375,nm5519454
tt9916808  nm5519375,nm5519454
tt9916810                   \N
tt9916812  nm5519454,nm5519375
tt9916814  nm5519454,nm5519375
tt9916816  nm5519375,nm5519454
tt9916818  nm5519454,nm5519375
tt9916820  nm5519375,nm5519454
tt9916822  nm5519454,nm5519375
tt9916824  nm5519454,nm5519375
tt9916826  nm5519375,nm5519454
tt9916830            nm4289598
tt9916832  nm5519454,nm5519375
tt9916834  nm5519454,nm5519375
tt9916836  nm5519454,nm5519375
tt9916838  nm5519375,nm5519454
tt9916840            nm0996406
tt9916842  nm5519375,nm5519454
tt9916844  nm5519375,nm5519454
tt9916846  nm5519454,nm5519375
tt9916848  nm5519375,nm5519454
tt9916850  nm5519375,nm5519454
tt9916852  nm5519375,nm5519454
tt9916856           nm10538645
tt9916880            nm0996406

[5953930 rows x 1 columns]

In [23]:
person_df =pd.read_csv('/Users/rakeshm/downloads/name_data.tsv.gz', delimiter = '\t', header=0, 
                       usecols=(0,1), names=['person_ID', 'name'])

In [24]:
person_df

         person_ID                 name
0        nm0000001         Fred Astaire
1        nm0000002        Lauren Bacall
2        nm0000003      Brigitte Bardot
3        nm0000004         John Belushi
4        nm0000005       Ingmar Bergman
5        nm0000006       Ingrid Bergman
6        nm0000007      Humphrey Bogart
7        nm0000008        Marlon Brando
8        nm0000009       Richard Burton
9        nm0000010         James Cagney
10       nm0000011          Gary Cooper
11       nm0000012          Bette Davis
12       nm0000013            Doris Day
13       nm0000014  Olivia de Havilland
14       nm0000015           James Dean
15       nm0000016      Georges Delerue
16       nm0000017     Marlene Dietrich
17       nm0000018         Kirk Douglas
18       nm0000019     Federico Fellini
19       nm0000020          Henry Fonda
20       nm0000021        Joan Fontaine
21       nm0000022          Clark Gable
22       nm0000023         Judy Garland
23       nm0000024         John Gielgud
24       nm0000025      Jerry Goldsmith
25       nm0000026           Cary Grant
26       nm0000027        Alec Guinness
27       nm0000028        Rita Hayworth
28       nm0000029    Margaux Hemingway
29       nm0000030       Audrey Hepburn
...            ...                  ...
9405162  nm9993689         Chris Bailey
9405163  nm9993690         David Jewell
9405164  nm9993691      Ursula Gehrmann
9405165  nm9993692        Shiela Martin
9405166  nm9993693      Anketa Maharana
9405167  nm9993694       Chinmay Mishra
9405168  nm9993696     Ibrahim-Aloduley
9405169  nm9993697       Zakariya Ganim
9405170  nm9993698            Sebi John
9405171  nm9993699           Dani Jacob
9405172  nm9993700           Sexy Angel
9405173  nm9993701     Sanjai Kuriakose
9405174  nm9993702           Liz Matory
9405175  nm9993703      James Craigmyle
9405176  nm9993704   Wojciech Kolodziej
9405177  nm9993705        Bozena Zegert
9405178  nm9993706     Michal Jackowski
9405179  nm9993707       Alexandra Rago
9405180  nm9993708           Eli Bevins
9405181  nm9993709            Lu Bevins
9405182  nm9993710    Nestor Rudnytskyy
9405183  nm9993711        David Gluzman
9405184  nm9993712      Corny O'Connell
9405185  nm9993713        Sambit Mishra
9405186  nm9993714    Romeo del Rosario
9405187  nm9993715        Stephen Crowe
9405188  nm9993716        Essias Loberg
9405189  nm9993717   Harikrishnan Rajan
9405190  nm9993718          Aayush Nair
9405191  nm9993719           Andre Hill

[9405192 rows x 2 columns]

In [25]:
person_df.set_index('person_ID', inplace =True)

In [26]:
person_df

                          name
person_ID
nm0000001         Fred Astaire
nm0000002        Lauren Bacall
nm0000003      Brigitte Bardot
nm0000004         John Belushi
nm0000005       Ingmar Bergman
nm0000006       Ingrid Bergman
nm0000007      Humphrey Bogart
nm0000008        Marlon Brando
nm0000009       Richard Burton
nm0000010         James Cagney
nm0000011          Gary Cooper
nm0000012          Bette Davis
nm0000013            Doris Day
nm0000014  Olivia de Havilland
nm0000015           James Dean
nm0000016      Georges Delerue
nm0000017     Marlene Dietrich
nm0000018         Kirk Douglas
nm0000019     Federico Fellini
nm0000020          Henry Fonda
nm0000021        Joan Fontaine
nm0000022          Clark Gable
nm0000023         Judy Garland
nm0000024         John Gielgud
nm0000025      Jerry Goldsmith
nm0000026           Cary Grant
nm0000027        Alec Guinness
nm0000028        Rita Hayworth
nm0000029    Margaux Hemingway
nm0000030       Audrey Hepburn
...                        ...
nm9993689         Chris Bailey
nm9993690         David Jewell
nm9993691      Ursula Gehrmann
nm9993692        Shiela Martin
nm9993693      Anketa Maharana
nm9993694       Chinmay Mishra
nm9993696     Ibrahim-Aloduley
nm9993697       Zakariya Ganim
nm9993698            Sebi John
nm9993699           Dani Jacob
nm9993700           Sexy Angel
nm9993701     Sanjai Kuriakose
nm9993702           Liz Matory
nm9993703      James Craigmyle
nm9993704   Wojciech Kolodziej
nm9993705        Bozena Zegert
nm9993706     Michal Jackowski
nm9993707       Alexandra Rago
nm9993708           Eli Bevins
nm9993709            Lu Bevins
nm9993710    Nestor Rudnytskyy
nm9993711        David Gluzman
nm9993712      Corny O'Connell
nm9993713        Sambit Mishra
nm9993714    Romeo del Rosario
nm9993715        Stephen Crowe
nm9993716        Essias Loberg
nm9993717   Harikrishnan Rajan
nm9993718          Aayush Nair
nm9993719           Andre Hill

[9405192 rows x 1 columns]

In [47]:

#Merge movie_crew_df into df with IDs and drop the columns
pdd = pd.merge(df, movie_crew_df, on = 'ID', how = 'inner')
pdd.head()
#pdd.dropna(inplace=True)

,title,year,rating,votes,duration,genres,director_ids
ID,,,,,,,
tt0111161,The Shawshank Redemption,1994,9.2,619479,8520,Crime|Drama,nm0001104
tt0110912,Pulp Fiction,1994,9.0,490065,9240,Crime|Thriller,nm0000233
tt0137523,Fight Club,1999,8.8,458173,8340,Drama|Mystery|Thriller,nm0000399
tt0133093,The Matrix,1999,8.7,448114,8160,Action|Adventure|Sci-Fi,"nm0905154,nm0905152"
tt1375666,Inception,2010,8.9,385149,8880,Action|Adventure|Sci-Fi|Thriller,nm0634240

In [48]:
pdd.isna().sum()

title           0
year            0
rating          0
votes           0
duration        0
genres          0
director_ids    0
dtype: int64

In [50]:
#Remove movies with more than one director and rename director_ids => director_id
pdd = pdd.loc[pdd["director_ids"].str.len()==9]

In [53]:
pdd.head()

,title,year,rating,votes,duration,genres,director_ids
ID,,,,,,,
tt0111161,The Shawshank Redemption,1994,9.2,619479,8520,Crime|Drama,nm0001104
tt0110912,Pulp Fiction,1994,9.0,490065,9240,Crime|Thriller,nm0000233
tt0137523,Fight Club,1999,8.8,458173,8340,Drama|Mystery|Thriller,nm0000399
tt1375666,Inception,2010,8.9,385149,8880,Action|Adventure|Sci-Fi|Thriller,nm0634240
tt0109830,Forrest Gump,1994,8.7,368994,8520,Comedy|Drama|Romance,nm0000709

In [56]:
pdd.rename(columns = {"director_ids":"director_id"}, inplace=True)

In [57]:
pdd.head()

,title,year,rating,votes,duration,genres,director_id
ID,,,,,,,
tt0111161,The Shawshank Redemption,1994,9.2,619479,8520,Crime|Drama,nm0001104
tt0110912,Pulp Fiction,1994,9.0,490065,9240,Crime|Thriller,nm0000233
tt0137523,Fight Club,1999,8.8,458173,8340,Drama|Mystery|Thriller,nm0000399
tt1375666,Inception,2010,8.9,385149,8880,Action|Adventure|Sci-Fi|Thriller,nm0634240
tt0109830,Forrest Gump,1994,8.7,368994,8520,Comedy|Drama|Romance,nm0000709

In [60]:
#Merge df with person_df on director_id, remove director_id and person_ID columns, rename name => director

phd= pd.merge(pdd, person_df, left_on='director_id', right_on='person_ID', how='inner')

In [62]:
phd.head()

,title,year,rating,votes,duration,genres,director_id,name
0,The Shawshank Redemption,1994,9.2,619479,8520,Crime|Drama,nm0001104,Frank Darabont
1,The Green Mile,1999,8.4,243660,11340,Crime|Drama|Fantasy|Mystery,nm0001104,Frank Darabont
2,The Mist,2007,7.4,90987,7560,Horror|Sci-Fi|Thriller,nm0001104,Frank Darabont
3,The Majestic,2001,6.8,27241,9120,Drama|Romance,nm0001104,Frank Darabont
4,Pulp Fiction,1994,9.0,490065,9240,Crime|Thriller,nm0000233,Quentin Tarantino

In [66]:
phd.drop(columns = 'director_id', axis=1, inplace=True)
phd.head()

,title,year,rating,votes,duration,genres,name
0,The Shawshank Redemption,1994,9.2,619479,8520,Crime|Drama,Frank Darabont
1,The Green Mile,1999,8.4,243660,11340,Crime|Drama|Fantasy|Mystery,Frank Darabont
2,The Mist,2007,7.4,90987,7560,Horror|Sci-Fi|Thriller,Frank Darabont
3,The Majestic,2001,6.8,27241,9120,Drama|Romance,Frank Darabont
4,Pulp Fiction,1994,9.0,490065,9240,Crime|Thriller,Quentin Tarantino

In [67]:
phd.rename(columns = {"name":"director"}, inplace=True)

In [68]:
phd.head()

,title,year,rating,votes,duration,genres,director
0,The Shawshank Redemption,1994,9.2,619479,8520,Crime|Drama,Frank Darabont
1,The Green Mile,1999,8.4,243660,11340,Crime|Drama|Fantasy|Mystery,Frank Darabont
2,The Mist,2007,7.4,90987,7560,Horror|Sci-Fi|Thriller,Frank Darabont
3,The Majestic,2001,6.8,27241,9120,Drama|Romance,Frank Darabont
4,Pulp Fiction,1994,9.0,490065,9240,Crime|Thriller,Quentin Tarantino